import { axiosClient } from "@lib/api/axios"
import type { GridParams } from "@/types"
import type { Matter, CreateMatterDto, MatterShortInfo } from "./matters.types"
function toModel(r: Record<string,unknown>): Matter { return { id:String(r.id??""), title:String(r.title??""), matterSequence:r.matterSequence as string, billingType:String(r.billingType??""), status:r.status as string, client:r.client as Matter["client"], responsibleAttorney:r.responsibleAttorney as Matter["responsibleAttorney"], department:r.department as Matter["department"], practiceArea:r.practiceArea as Matter["practiceArea"], caseNo:r.caseNo as string, openDate:r.openDate as string, description:r.description as string } }
export const mattersApi = {
  async getAll(p: GridParams) { const res=await axiosClient.post("/api/report/matter/mini/filter/page/v2",{},{params:{pageNumber:p.page,pageSize:p.pageSize,searchText:p.filters.searchText??"",clientId:p.filters.clientId??""}}); const d=res.data?.data??res.data; return {content:(d.content??[]).map(toModel),totalElements:d.totalElements??0,totalPages:d.totalPages??0,number:d.number??0,size:d.size??p.pageSize,first:d.first??true,last:d.last??true,empty:d.empty??true} },
  async getById(matterId: string): Promise<Matter> { const res=await axiosClient.post("/api/matter/get/by/id",null,{params:{matterId}}); return toModel(res.data?.data??res.data) },
  async search(q: string): Promise<MatterShortInfo[]> { const res=await axiosClient.get("/api/matter/get/short-info",{params:{searchText:q,pageNumber:0,pageSize:50}}); return res.data?.content??res.data?.data?.content??[] },
  async create(dto: CreateMatterDto): Promise<{id:string}> { const res=await axiosClient.post("/api/matter/add",{title:dto.title,client:{id:dto.clientId},billingType:dto.billingType,responsibleAttorney:dto.responsibleAttorneyId?{id:dto.responsibleAttorneyId}:undefined,practiceArea:dto.practiceAreaId?{id:dto.practiceAreaId}:undefined,department:dto.departmentId?{id:dto.departmentId}:undefined,description:dto.description,caseNo:dto.caseNo,openDate:dto.openDate}); return {id:res.data?.data?.id??""} },
  async update(matterId: string, dto: Partial<CreateMatterDto>): Promise<void> { await axiosClient.post("/api/matter/edit",{matterId,...dto}) },
  async close(matterId: string, closeDate: string, closeReason: string, closingNote: string): Promise<void> { await axiosClient.post("/api/matter/close",{matterId,closeDate,closeReason,closingNote}) },
}
