import HistoryIcon from '@mui/icons-material/History'
import EmailIcon from '@mui/icons-material/Email'
import { PERMISSIONS } from './permissions'

/**
 * Fallback navigation config — used only as shape reference and loading state.
 * At runtime this is OVERRIDDEN by /api/user/get/access/menu response.
 *
 * Structure mirrors Next.js App Router file paths so sidebar links
 * stay in sync with the directory structure.
 */

export type NavItem = {
  id: string
  title: string            // translation key: nav.{id}
  path?: string
  icon?: string            // Material icon name string
  permission?: string      // hide if user lacks this permission
  children?: NavItem[]
  badge?: string           // dynamic badge (count from API)
  dividerAfter?: boolean
}

export const navigationConfig: NavItem[] = [
  {
    id: 'dashboard',
    title: 'nav.dashboard',
    path: '/dashboard',
    icon: 'DashboardOutlined',
    permission: PERMISSIONS.DASHBOARD_VIEW,
  },
  {
    id: 'department-analytics',
    title: 'nav.analytics',
    path: '/department/analytics',
    icon: 'AnalyticsOutlined',
    permission: PERMISSIONS.DASHBOARD_VIEW,
  },
  {
    id: 'crm',
    title: 'nav.crm',
    icon: 'PeopleOutlined',
    children: [
      {
        id: 'leads',
        title: 'nav.leads',
        path: '/leads',
        icon: 'TrendingUpOutlined',
        permission: PERMISSIONS.LEADS_VIEW,
      },
      {
        id: 'my-leads',
        title: 'nav.myLeads',
        path: '/my-leads',
        icon: 'PersonSearchOutlined',
        permission: PERMISSIONS.MY_LEADS_VIEW,
      },
      {
        id: 'clients',
        title: 'nav.clients',
        path: '/clients',
        icon: 'BusinessOutlined',
        permission: PERMISSIONS.CLIENTS_VIEW,
      },
      {
        id: 'vendors',
        title: 'nav.vendors',
        path: '/vendors',
        icon: 'StorefrontOutlined',
        permission: PERMISSIONS.VENDORS_VIEW,
      },
      {
        id: 'internal-leads',
        title: 'nav.internalLeads',
        path: '/internal-leads',
        icon: 'PersonSearchOutlined',
        permission: PERMISSIONS.LEADS_VIEW,
      },
      {
        id: 'client-transfer',
        title: 'nav.clientTransfer',
        path: '/clients/transfer',
        icon: 'ShareOutlined',
        permission: PERMISSIONS.CLIENTS_VIEW,
      },
      {
        id: 'referral-partners',
        title: 'nav.referralPartners',
        path: '/clients/referral-partners',
        icon: 'PeopleOutlined',
        permission: PERMISSIONS.CLIENTS_VIEW,
      },
    ],
  },
  {
    id: 'matters',
    title: 'nav.matters',
    icon: 'GavelOutlined',
    children: [
      {
        id: 'matters-list',
        title: 'nav.matters',
        path: '/matters',
        icon: 'FolderOutlined',
        permission: PERMISSIONS.MATTERS_VIEW,
      },
      {
        id: 'request-matters',
        title: 'nav.requestMatters',
        path: '/matters/requests',
        icon: 'AssignmentOutlined',
        permission: PERMISSIONS.MATTERS_VIEW,
      },
      {
        id: 'check-conflict',
        title: 'nav.checkConflict',
        path: '/matters/check-conflict',
        icon: 'FindInPageOutlined',
        permission: PERMISSIONS.MATTERS_VIEW,
      },
      {
        id: 'short-matters',
        title: 'nav.shortMatters',
        path: '/matters/short',
        icon: 'DescriptionOutlined',
        permission: PERMISSIONS.MATTERS_VIEW,
      },
      {
        id: 'pending-matters',
        title: 'nav.pendingMatters',
        path: '/matters/pending',
        icon: 'PendingActionsOutlined',
        permission: PERMISSIONS.MATTERS_VIEW,
      },
      {
        id: 'hearings',
        title: 'nav.hearings',
        path: '/hearings',
        icon: 'GavelOutlined',
        permission: PERMISSIONS.MATTERS_VIEW,
      },
      {
        id: 'hearing-history',
        title: 'nav.hearingHistory',
        path: '/hearings/history',
        icon: 'HistoryOutlined',
        permission: PERMISSIONS.MATTERS_VIEW,
      },
      {
        id: 'document-reminders',
        title: 'nav.documentReminders',
        path: '/document-reminders',
        icon: 'EventNoteOutlined',
        permission: PERMISSIONS.MATTERS_VIEW,
      },
    ],
  },
  {
    id: 'time-tasks',
    title: 'nav.timeAndTasks',
    icon: 'TimerOutlined',
    children: [
      {
        id: 'time-log-entries',
        title: 'nav.timeLogEntries',
        path: '/time-log-entries',
        icon: 'AccessTimeOutlined',
        permission: PERMISSIONS.TIMELOGS_VIEW,
      },
      {
        id: 'matter-selection',
        title: 'nav.matterSelection',
        path: '/matter-selection',
        icon: 'FactCheckOutlined',
        permission: PERMISSIONS.TIMELOGS_CREATE,
      },
      {
        id: 'activities',
        title: 'nav.activities',
        path: '/activities',
        icon: 'HistoryOutlined',
        permission: PERMISSIONS.TIMELOGS_VIEW,
      },
      {
        id: 'tasks',
        title: 'nav.tasks',
        path: '/tasks',
        icon: 'TaskAltOutlined',
        permission: PERMISSIONS.TASKS_VIEW,
      },
      {
        id: 'task-templates',
        title: 'nav.taskTemplates',
        path: '/tasks/templates',
        icon: 'LibraryBooksOutlined',
        permission: PERMISSIONS.TASKS_VIEW,
      },
      {
        id: 'multi-step-tasks',
        title: 'nav.multiStepTasks',
        path: '/tasks/multi-step',
        icon: 'ChecklistOutlined',
        permission: PERMISSIONS.TASKS_VIEW,
      },
      {
        id: 'calendar',
        title: 'nav.calendar',
        path: '/calendar',
        icon: 'CalendarMonthOutlined',
        permission: PERMISSIONS.CALENDAR_VIEW,
      },
    ],
  },
  {
    id: 'billing',
    title: 'nav.billing',
    icon: 'ReceiptOutlined',
    children: [
      {
        id: 'billings',
        title: 'nav.billing',
        path: '/billings',
        icon: 'ReceiptLongOutlined',
        permission: PERMISSIONS.BILLING_VIEW,
      },
      {
        id: 'generate-bill',
        title: 'nav.generateBill',
        path: '/billing',
        icon: 'RequestPageOutlined',
        permission: PERMISSIONS.BILLING_VIEW,
      },
      {
        id: 'payment',
        title: 'nav.payment',
        path: '/payment',
        icon: 'PaymentsOutlined',
        permission: PERMISSIONS.BILLING_VIEW,
      },
      {
        id: 'invoices',
        title: 'nav.invoices',
        path: '/billings',
        icon: 'RequestPageOutlined',
        permission: PERMISSIONS.BILLING_VIEW,
      },
      {
        id: 'expense-billing',
        title: 'nav.expenseBilling',
        path: '/billings/expense',
        icon: 'PaymentsOutlined',
        permission: PERMISSIONS.BILLING_VIEW,
      },
      {
        id: 'contingent-billing',
        title: 'nav.contingentBilling',
        path: '/billings/contingent',
        icon: 'PercentOutlined',
        permission: PERMISSIONS.BILLING_VIEW,
      },
      {
        id: 'non-contingent-billing',
        title: 'nav.nonContingentBilling',
        path: '/billings/non-contingent',
        icon: 'PriceChangeOutlined',
        permission: PERMISSIONS.BILLING_VIEW,
      },
      {
        id: 'success-rate-billing',
        title: 'nav.successRateBilling',
        path: '/billings/success-rate',
        icon: 'EmojiEventsOutlined',
        permission: PERMISSIONS.BILLING_VIEW,
      },
      {
        id: 'enforcement-billing',
        title: 'nav.enforcementBilling',
        path: '/billings/enforcement',
        icon: 'GavelOutlined',
        permission: PERMISSIONS.BILLING_VIEW,
      },
      {
        id: 'receipts',
        title: 'nav.receipts',
        path: '/billings/receipts',
        icon: 'ReceiptOutlined',
        permission: PERMISSIONS.BILLING_VIEW,
      },
      {
        id: 'credit-notes',
        title: 'nav.creditNotes',
        path: '/billings/credit-notes',
        icon: 'PaidOutlined',
        permission: PERMISSIONS.BILLING_VIEW,
      },
      {
        id: 'retainer-billing',
        title: 'nav.retainerBilling',
        path: '/billings/retainer',
        icon: 'AccountBalanceWalletOutlined',
        permission: PERMISSIONS.BILLING_VIEW,
      },
      {
        id: 'retainer-statements',
        title: 'nav.retainerStatements',
        path: '/billings/retainer-statements',
        icon: 'DescriptionOutlined',
        permission: PERMISSIONS.BILLING_VIEW,
      },
      {
        id: 'retainer-history',
        title: 'nav.retainerHistory',
        path: '/billings/retainer-history',
        icon: 'HistoryOutlined',
        permission: PERMISSIONS.BILLING_VIEW,
      },
      {
        id: 'write-off',
        title: 'nav.writeOff',
        path: '/billings/write-off',
        icon: 'PriceChangeOutlined',
        permission: PERMISSIONS.BILLING_VIEW,
      },
      {
        id: 'billing-history',
        title: 'nav.billingHistory',
        path: '/billings/history',
        icon: 'HistoryOutlined',
        permission: PERMISSIONS.BILLING_VIEW,
      },
      {
        id: 'translation-courier',
        title: 'nav.translationCourier',
        path: '/billings/translation-courier',
        icon: 'LocalShippingOutlined',
        permission: PERMISSIONS.BILLING_VIEW,
      },
    ],
  },
  {
    id: 'approvals',
    title: 'nav.approvals',
    icon: 'CheckCircleOutlined',
    children: [
      {
        id: 'invoice-approval',
        title: 'nav.invoiceApproval',
        path: '/approvals/invoice',
        icon: 'FactCheckOutlined',
        permission: PERMISSIONS.BILLING_APPROVE,
      },
      {
        id: 'lfa-approval',
        title: 'nav.lfaApproval',
        path: '/approvals/lfa',
        icon: 'AssignmentTurnedInOutlined',
        permission: PERMISSIONS.LFA_APPROVE,
      },
      {
        id: 'task-approval',
        title: 'nav.taskApproval',
        path: '/approvals/task',
        icon: 'AssignmentOutlined',
        permission: PERMISSIONS.TASKS_VIEW,
      },
      {
        id: 'department-invoice-approval',
        title: 'nav.departmentInvoiceApproval',
        path: '/approvals/department-invoice',
        icon: 'FactCheckOutlined',
        permission: PERMISSIONS.BILLING_APPROVE,
      },
      {
        id: 'department-activity-approval',
        title: 'nav.departmentActivityApproval',
        path: '/approvals/department-activity',
        icon: 'RateReviewOutlined',
        permission: PERMISSIONS.TIMELOGS_APPROVE,
      },
    ],
  },
  {
    id: 'lfa',
    title: 'nav.lfa',
    icon: 'ArticleOutlined',
    children: [
      {
        id: 'lfa-list',
        title: 'nav.lfa',
        path: '/lfa',
        icon: 'DescriptionOutlined',
        permission: PERMISSIONS.LFA_VIEW,
      },
      {
        id: 'default-lfas',
        title: 'nav.defaultLfas',
        path: '/lfa/default',
        icon: 'LibraryBooksOutlined',
        permission: PERMISSIONS.LFA_VIEW,
      },
      {
        id: 'lfa-reports',
        title: 'nav.lfaReports',
        path: '/lfa/reports',
        icon: 'SummarizeOutlined',
        permission: PERMISSIONS.LFA_VIEW,
      },
      {
        id: 'client-lfas',
        title: 'nav.clientLfas',
        path: '/lfa/client',
        icon: 'ManageAccountsOutlined',
        permission: PERMISSIONS.LFA_VIEW,
      },
    ],
  },
  {
    id: 'timelogs',
    title: 'nav.timelogsReview',
    icon: 'RateReviewOutlined',
    children: [
      {
        id: 'timelogs-review',
        title: 'nav.timelogsReview',
        path: '/timelogs/review',
        icon: 'ReviewsOutlined',
        permission: PERMISSIONS.TIMELOGS_APPROVE,
      },
      {
        id: 'timelogs-pre-approval',
        title: 'nav.timelogsPreApproval',
        path: '/timelogs/pre-approval',
        icon: 'PendingActionsOutlined',
        permission: PERMISSIONS.TIMELOGS_APPROVE,
      },
      {
        id: 'timelogs-approval',
        title: 'nav.timelogsApproval',
        path: '/timelogs/approval',
        icon: 'HowToRegOutlined',
        permission: PERMISSIONS.TIMELOGS_APPROVE,
      },
      {
        id: 'timelogs-pending',
        title: 'nav.pendingTimelogs',
        path: '/timelogs/pending',
        icon: 'HourglassTopOutlined',
        permission: PERMISSIONS.TIMELOGS_APPROVE,
      },
      {
        id: 'timelogs-approved',
        title: 'nav.approvedTimelogs',
        path: '/timelogs/approved',
        icon: 'CheckCircleOutlined',
        permission: PERMISSIONS.TIMELOGS_VIEW,
      },
    ],
  },
  {
    id: 'reports',
    title: 'nav.reports',
    icon: 'BarChartOutlined',
    permission: PERMISSIONS.REPORTS_VIEW,
    children: [
      { id: 'reports-hub',       title: 'nav.reportsHub',      path: '/reports',                  icon: 'GridViewOutlined', permission: PERMISSIONS.REPORTS_VIEW },
      { id: 'wip-reports',       title: 'nav.wipReports',      path: '/reports/wip',              icon: 'WorkOutlineOutlined', permission: PERMISSIONS.REPORTS_VIEW },
      { id: 'billed-amount',     title: 'nav.billedAmount',    path: '/reports/billed-amount',    icon: 'PaidOutlined', permission: PERMISSIONS.REPORTS_VIEW },
      { id: 'matter-billing',    title: 'nav.matterBilling',   path: '/reports/matter-billing',   icon: 'AccountBalanceOutlined', permission: PERMISSIONS.REPORTS_VIEW },
      { id: 'utilization',       title: 'nav.utilization',     path: '/reports/utilization',      icon: 'SpeedOutlined', permission: PERMISSIONS.REPORTS_VIEW },
      { id: 'activity-history',  title: 'nav.activityHistory', path: '/reports/activity-history', icon: 'HistoryOutlined', permission: PERMISSIONS.REPORTS_VIEW },
      { id: 'collections',       title: 'nav.collections',     path: '/reports/collections',      icon: 'CollectionsBookmarkOutlined', permission: PERMISSIONS.REPORTS_VIEW },
      { id: 'margin-erosion',    title: 'nav.marginErosion',   path: '/reports/margin-erosion',   icon: 'TrendingDownOutlined', permission: PERMISSIONS.REPORTS_VIEW },
      { id: 'aging',             title: 'nav.aging',           path: '/reports/aging',            icon: 'HourglassBottomOutlined', permission: PERMISSIONS.REPORTS_VIEW },
      { id: 'dues',              title: 'nav.dues',            path: '/reports/dues',             icon: 'MoneyOffOutlined', permission: PERMISSIONS.REPORTS_VIEW },
      { id: 'matters-report',    title: 'nav.mattersReport',   path: '/reports/matters',          icon: 'FolderOpenOutlined', permission: PERMISSIONS.REPORTS_VIEW },
      { id: 'tasks-report',      title: 'nav.tasksReport',     path: '/reports/tasks',            icon: 'ChecklistOutlined', permission: PERMISSIONS.REPORTS_VIEW },
      { id: 'hearings-report',   title: 'nav.hearingsReport',  path: '/reports/hearings',         icon: 'GavelOutlined', permission: PERMISSIONS.REPORTS_VIEW },
      { id: 'profit-loss',       title: 'nav.profitLoss',      path: '/reports/profit-loss',      icon: 'ShowChartOutlined', permission: PERMISSIONS.REPORTS_VIEW },
      { id: 'attorney-revenue',  title: 'nav.attorneyRevenue', path: '/reports/attorney-revenue', icon: 'AccountBalanceWalletOutlined', permission: PERMISSIONS.REPORTS_VIEW },
      { id: 'referral',          title: 'nav.referral',        path: '/reports/referral',         icon: 'ShareOutlined', permission: PERMISSIONS.REPORTS_VIEW },
      { id: 'non-converted-leads', title: 'nav.nonConvertedLeads', path: '/reports/non-converted-leads', icon: 'PersonOffOutlined', permission: PERMISSIONS.REPORTS_VIEW },
      { id: 'purged-discounted', title: 'nav.purgedDiscounted', path: '/reports/purged-discounted', icon: 'DeleteSweepOutlined', permission: PERMISSIONS.REPORTS_VIEW },
      { id: 'cost-analysis',     title: 'nav.costAnalysis',    path: '/reports/cost-analysis',    icon: 'AnalyticsOutlined', permission: PERMISSIONS.REPORTS_VIEW },
      { id: 'zoho-outstanding',  title: 'nav.zohoOutstanding', path: '/reports/zoho-outstanding', icon: 'ReceiptLongOutlined', permission: PERMISSIONS.REPORTS_VIEW },
      { id: 'invoices-report',   title: 'nav.invoicesReport',  path: '/reports/invoices',         icon: 'ReceiptOutlined', permission: PERMISSIONS.REPORTS_VIEW },
      { id: 'leads-report',      title: 'nav.leadsReport',     path: '/reports/leads',            icon: 'PersonSearchOutlined', permission: PERMISSIONS.REPORTS_VIEW },
      { id: 'activities-report', title: 'nav.activitiesReport', path: '/reports/activities',      icon: 'AccessTimeOutlined', permission: PERMISSIONS.REPORTS_VIEW },
      { id: 'deposit-balance',   title: 'nav.depositBalance',  path: '/reports/deposit-balance',  icon: 'SavingsOutlined', permission: PERMISSIONS.REPORTS_VIEW },
      { id: 'user-timelog-entries', title: 'nav.userTimelogEntries', path: '/reports/user-timelog-entries', icon: 'AccessTimeOutlined', permission: PERMISSIONS.REPORTS_VIEW },
      { id: 'rating', title: 'nav.ratingReport', path: '/reports/rating', icon: 'EmojiEventsOutlined', permission: PERMISSIONS.REPORTS_VIEW },
      { id: 'posts', title: 'nav.postsReport', path: '/reports/posts', icon: 'ArticleOutlined', permission: PERMISSIONS.REPORTS_VIEW },
      { id: 'retainer-statement', title: 'nav.retainerStatementReport', path: '/reports/retainer-statement', icon: 'AccountBalanceWalletOutlined', permission: PERMISSIONS.REPORTS_VIEW },
      { id: 'matter-summary', title: 'nav.matterSummary', path: '/reports/matter-summary', icon: 'SummarizeOutlined', permission: PERMISSIONS.REPORTS_VIEW },
      { id: 'closed-matters', title: 'nav.closedMatters', path: '/reports/closed-matters', icon: 'FolderOutlined', permission: PERMISSIONS.REPORTS_VIEW },
      { id: 'fee-earner-billed', title: 'nav.feeEarnerBilled', path: '/reports/fee-earner-billed', icon: 'PaidOutlined', permission: PERMISSIONS.REPORTS_VIEW },
      { id: 'task-average', title: 'nav.taskAverage', path: '/reports/task-average', icon: 'ChecklistOutlined', permission: PERMISSIONS.REPORTS_VIEW },
      { id: 'fixed-balance', title: 'nav.fixedBalance', path: '/reports/fixed-balance', icon: 'AccountBalanceOutlined', permission: PERMISSIONS.REPORTS_VIEW },
      { id: 'billing-by-lfa', title: 'nav.billingByLfa', path: '/reports/billing-by-lfa', icon: 'ReceiptOutlined', permission: PERMISSIONS.REPORTS_VIEW },
      { id: 'billable-by-department', title: 'nav.billableByDepartment', path: '/reports/billable-by-department', icon: 'BarChartOutlined', permission: PERMISSIONS.REPORTS_VIEW },
      { id: 'audit', title: 'nav.auditReport', path: '/reports/audit', icon: 'HistoryOutlined', permission: PERMISSIONS.REPORTS_VIEW },
      { id: 'onedrive', title: 'nav.onedriveReport', path: '/reports/onedrive', icon: 'CloudOutlined', permission: PERMISSIONS.REPORTS_VIEW },
      { id: 'favourite-clients', title: 'nav.favouriteClients', path: '/reports/favourite-clients', icon: 'PeopleOutlined', permission: PERMISSIONS.REPORTS_VIEW },
      { id: 'fixedfee-revenue-allocation', title: 'nav.fixedFeeRevenueAllocation', path: '/reports/fixedfee-revenue-allocation', icon: 'PercentOutlined', permission: PERMISSIONS.REPORTS_VIEW },
      { id: 'procured-by', title: 'nav.procuredBy', path: '/reports/procured-by', icon: 'TrendingUpOutlined', permission: PERMISSIONS.REPORTS_VIEW },
      { id: 'lead-value', title: 'nav.leadValue', path: '/reports/lead-value', icon: 'PersonSearchOutlined', permission: PERMISSIONS.REPORTS_VIEW },
      { id: 'leads-reduction', title: 'nav.leadsReduction', path: '/reports/leads-reduction', icon: 'TrendingDownOutlined', permission: PERMISSIONS.REPORTS_VIEW },
      { id: 'matter-revenue-summary', title: 'nav.matterRevenueSummary', path: '/reports/matter-revenue-summary', icon: 'ShowChartOutlined', permission: PERMISSIONS.REPORTS_VIEW },
      { id: 'estimate-hours-by-designation', title: 'nav.estimateHoursByDesignation', path: '/reports/estimate-hours-by-designation', icon: 'HourglassBottomOutlined', permission: PERMISSIONS.REPORTS_VIEW },
      { id: 'revenue-budget', title: 'nav.revenueBudget', path: '/reports/revenue-budget', icon: 'SavingsOutlined', permission: PERMISSIONS.REPORTS_VIEW },
      { id: 'billing-rate-analysis', title: 'nav.billingRateAnalysis', path: '/reports/billing-rate-analysis', icon: 'SpeedOutlined', permission: PERMISSIONS.REPORTS_VIEW },
      { id: 'matter-billing-snapshot', title: 'nav.matterBillingSnapshot', path: '/reports/matter-billing-snapshot', icon: 'AnalyticsOutlined', permission: PERMISSIONS.REPORTS_VIEW },
      { id: 'margin-erosion-cache', title: 'nav.marginErosionCache', path: '/reports/margin-erosion-cache', icon: 'TrendingDownOutlined', permission: PERMISSIONS.REPORTS_VIEW },
    ],
  },
  {
    id: 'team',
    title: 'nav.team',
    icon: 'GroupsOutlined',
    children: [
      { id: 'my-team',          title: 'nav.myTeam',         path: '/team',                    icon: 'GroupOutlined', permission: PERMISSIONS.TEAM_VIEW },
      { id: 'team-templates',   title: 'nav.teamTemplates',  path: '/team/templates',          icon: 'LibraryBooksOutlined', permission: PERMISSIONS.TEAM_VIEW },
      { id: 'hearing-calendar', title: 'nav.hearingCalendar',path: '/team/hearing-calendar',   icon: 'EventNoteOutlined', permission: PERMISSIONS.TEAM_VIEW },
      { id: 'upcoming-hearings', title: 'nav.upcomingHearings', path: '/team/upcoming-hearings', icon: 'GavelOutlined', permission: PERMISSIONS.TEAM_VIEW },
      { id: 'my-leaves', title: 'nav.myLeaves', path: '/leaves', icon: 'EventAvailableOutlined', permission: PERMISSIONS.LEAVES_VIEW },
      { id: 'leave-applications', title: 'nav.leaveApplications', path: '/leave-applications', icon: 'FactCheckOutlined', permission: PERMISSIONS.LEAVES_VIEW },
      { id: 'payrolls', title: 'nav.payrolls', path: '/payrolls', icon: 'PaymentsOutlined', permission: PERMISSIONS.PAYROLL_VIEW },
    ],
  },
  {
    id: 'integrations',
    title: 'nav.integrations',
    icon: 'IntegrationInstructionsOutlined',
    dividerAfter: false,
    children: [
      { id: 'email', title: 'nav.email', path: '/email', icon: 'EmailOutlined' },
      { id: 'onedrive', title: 'nav.oneDrive', path: '/integrations/onedrive', icon: 'CloudOutlined', permission: PERMISSIONS.ONEDRIVE_VIEW },
    ],
  },
  {
    id: 'budgeting',
    title: 'nav.budgeting',
    icon: 'AccountBalanceWalletOutlined',
    children: [
      { id: 'cost-cards',   title: 'nav.costCards',   path: '/budgeting/cost-cards',   icon: 'CreditCardOutlined', permission: PERMISSIONS.BUDGETING_VIEW },
      { id: 'budget-cards', title: 'nav.budgetCards', path: '/budgeting/budget-cards', icon: 'SavingsOutlined', permission: PERMISSIONS.BUDGETING_VIEW },
      { id: 'rate-cards',   title: 'nav.rateCards',   path: '/budgeting/rate-cards',   icon: 'PriceChangeOutlined', permission: PERMISSIONS.BUDGETING_VIEW },
      { id: 'activity-rate-cards', title: 'nav.activityRateCards', path: '/rate-cards', icon: 'FactCheckOutlined', permission: PERMISSIONS.BUDGETING_VIEW },
    ],
  },
  {
    id: 'admin',
    title: 'nav.admin',
    icon: 'AdminPanelSettingsOutlined',
    dividerAfter: true,
    children: [
      { id: 'users',       title: 'nav.manageUsers', path: '/admin/users',       icon: 'ManageAccountsOutlined', permission: PERMISSIONS.USERS_VIEW },
      { id: 'admin-teams', title: 'nav.adminTeams', path: '/admin/teams', icon: 'GroupsOutlined', permission: PERMISSIONS.TEAM_MANAGE },
      { id: 'bank-accounts', title: 'nav.bankAccounts', path: '/admin/bank-accounts', icon: 'AccountBalanceOutlined', permission: PERMISSIONS.BANK_ACCOUNTS_VIEW },
      { id: 'groups',      title: 'nav.groups',      path: '/admin/groups',      icon: 'GroupWorkOutlined', permission: PERMISSIONS.GROUPS_VIEW },
      { id: 'permissions', title: 'nav.permissions', path: '/admin/permissions', icon: 'LockOutlined', permission: PERMISSIONS.GROUPS_MANAGE },
      { id: 'individual-permissions', title: 'nav.individualPermissions', path: '/admin/individual-permissions', icon: 'ManageAccountsOutlined', permission: PERMISSIONS.GROUPS_MANAGE },
      { id: 'activity-access', title: 'nav.activityAccess', path: '/admin/activity-access', icon: 'HourglassTopOutlined', permission: PERMISSIONS.GROUPS_MANAGE },
      { id: 'extra-permissions', title: 'nav.extraPermissions', path: '/admin/extra-permissions', icon: 'LockOutlined', permission: PERMISSIONS.GROUPS_MANAGE },
      { id: 'locations',   title: 'nav.locations',   path: '/admin/locations',   icon: 'LocationOnOutlined', permission: PERMISSIONS.LOCATIONS_VIEW },
      { id: 'audit-log',   title: 'nav.auditLog',    path: '/admin/audit-log',   icon: 'HistoryOutlined', permission: PERMISSIONS.SETTINGS_VIEW },
      { id: 'settings',    title: 'nav.settings',    path: '/admin/settings',    icon: 'SettingsOutlined', permission: PERMISSIONS.SETTINGS_VIEW },
    ],
  },
  {
    id: 'tickets',
    title: 'nav.raisedTickets',
    path: '/tickets',
    icon: 'ConfirmationNumberOutlined',
    permission: PERMISSIONS.TICKETS_VIEW,
  },
]
