/**
 * Settings master registry — LMS SettingsContent tiles → v3 LookupManager / routes.
 */
export interface MasterConfig {
  key: string
  title: string
  description: string
  getUrl: string
  addUrl: string
  deleteUrl: string
  nameField: string
  statusChange?: boolean
  extraFields?: { key: string; label: string; type?: string }[]
  /** When set, hub tile navigates here instead of /masters/:key */
  href?: string
  section: "masters" | "settings"
  keywords?: string
}

/** Simple name-list masters managed via LookupManager */
export const LOOKUP_MASTERS: MasterConfig[] = [
  {
    key: "lead-status",
    title: "Lead Status Master",
    description: "Setting up lead status",
    getUrl: "/api/leads/get/status",
    addUrl: "/api/util/add/status",
    deleteUrl: "/api/util/update/status/delete",
    nameField: "statusName",
    section: "masters",
    keywords: "lead status",
  },
  {
    key: "lead-source",
    title: "Lead Source Master",
    description: "Setting up lead source master",
    getUrl: "/api/util/get/source/master?status=Active",
    addUrl: "/api/util/add/source/master",
    deleteUrl: "/api/util/source/master/status/change",
    nameField: "name",
    statusChange: true,
    section: "masters",
  },
  {
    key: "practice-area",
    title: "Practice area",
    description: "Setting up practice area master",
    getUrl: "/api/practicearea/get?fetchtype=all",
    addUrl: "/api/practicearea/add",
    deleteUrl: "/api/practicearea/change/status",
    nameField: "name",
    statusChange: true,
    section: "masters",
  },
  {
    key: "docs-type",
    title: "Documents Type",
    description: "Setting up documents type master",
    getUrl: "/api/util/list/doc/type",
    addUrl: "/api/util/add/doc/type",
    deleteUrl: "/api/util/change/doc/status",
    nameField: "name",
    statusChange: true,
    section: "masters",
  },
  {
    key: "rates",
    title: "Add Hourly Rate",
    description: "Set hourly rate of attorney",
    getUrl: "/api/util/get/hourly/rate",
    addUrl: "/api/util/add/hourly/rate",
    deleteUrl: "/api/util/hourly/rate/change/status",
    nameField: "rate",
    extraFields: [{ key: "designationId", label: "Designation ID" }],
    statusChange: true,
    section: "masters",
  },
  {
    key: "representative-designation",
    title: "Representative Designations",
    description: "Setting up Representative Designations master",
    getUrl: "/api/util/list/representing/designation",
    addUrl: "/api/util/add/representing/designation",
    deleteUrl: "/api/util/update/representing/status",
    nameField: "name",
    statusChange: true,
    section: "masters",
  },
  {
    key: "folders",
    title: "Add Folders Name",
    description: "Add folders name come under matter",
    getUrl: "/api/util/get/folder",
    addUrl: "/api/util/add/folder",
    deleteUrl: "/api/util/folder/change/status",
    nameField: "name",
    statusChange: true,
    section: "masters",
  },
  {
    key: "session",
    title: "Session Type",
    description: "Add session type",
    getUrl: "/api/util/get/session/type",
    addUrl: "/api/util/add/session/type",
    deleteUrl: "/api/util/session/type/change/status",
    nameField: "typeName",
    statusChange: true,
    section: "masters",
  },
  {
    key: "hearing-types",
    title: "Hearing Types",
    description: "Hearing Types",
    getUrl: "/api/hearing/list/type",
    addUrl: "/api/hearing/add/type",
    deleteUrl: "/api/hearing/type/change/status",
    nameField: "name",
    statusChange: true,
    section: "masters",
  },
  {
    key: "case-types",
    title: "Case Types",
    description: "Manage Case Types",
    getUrl: "/api/util/list/case/type",
    addUrl: "/api/util/add/case/type",
    deleteUrl: "/api/util/case/type/change/status",
    nameField: "name",
    statusChange: true,
    section: "masters",
  },
  {
    key: "locations",
    title: "Locations",
    description: "Add Locations",
    href: "/admin/locations",
    getUrl: "",
    addUrl: "",
    deleteUrl: "",
    nameField: "name",
    section: "masters",
  },
  {
    key: "designations",
    title: "Designations",
    description: "Manage Designations",
    getUrl: "/api/util/get/designation",
    addUrl: "/api/util/add/designation",
    deleteUrl: "/api/util/designation/change/status",
    nameField: "name",
    statusChange: true,
    section: "masters",
  },
  {
    key: "breakdowns",
    title: "Breakdowns",
    description: "Manage Breakdowns",
    getUrl: "/api/util/list/breakdown",
    addUrl: "/api/util/add/breakdown",
    deleteUrl: "/api/util/breakdown/change/status",
    nameField: "name",
    statusChange: true,
    section: "masters",
  },
  {
    key: "departments",
    title: "Departments",
    description: "Manage Department",
    getUrl: "/api/util/list/department",
    addUrl: "/api/util/add/department",
    deleteUrl: "/api/util/department/change/status",
    nameField: "name",
    statusChange: true,
    section: "masters",
  },
  {
    key: "party-opposing-type",
    title: "Party Opposing Type",
    description: "Manage Party Opposing Type",
    getUrl: "/api/util/list/party/opposing/type",
    addUrl: "/api/util/add/party/opposing/type",
    deleteUrl: "/api/util/party/opposing/type/change/status",
    nameField: "name",
    statusChange: true,
    section: "masters",
  },
  {
    key: "refer-client",
    title: "Refer Client",
    description: "Refer to Clients",
    getUrl: "/api/util/list/refer/client",
    addUrl: "/api/util/add/refer/client",
    deleteUrl: "/api/util/refer/client/change/status",
    nameField: "name",
    statusChange: true,
    section: "masters",
  },
  {
    key: "lfa-title",
    title: "LFA Title",
    description: "LFA Title",
    getUrl: "/api/util/list/lfa/title",
    addUrl: "/api/util/add/lfa/title",
    deleteUrl: "/api/util/lfa/title/change/status",
    nameField: "name",
    statusChange: true,
    section: "masters",
  },
  {
    key: "invoice-description",
    title: "Invoice Description",
    description: "Invoice Description Master",
    getUrl: "/api/util/list/invoice/description",
    addUrl: "/api/util/add/invoice/description",
    deleteUrl: "/api/util/invoice/description/change/status",
    nameField: "name",
    statusChange: true,
    section: "masters",
  },
  {
    key: "applicable-law",
    title: "Applicable Law",
    description: "Applicable Law Master",
    getUrl: "/api/util/list/applicable/law",
    addUrl: "/api/util/add/applicable/law",
    deleteUrl: "/api/util/applicable/law/change/status",
    nameField: "name",
    statusChange: true,
    section: "masters",
  },
  {
    key: "write-off-reason",
    title: "Write Off Reason",
    description: "Write Off Reason Master",
    getUrl: "/api/util/list/write-off/reason",
    addUrl: "/api/util/add/write-off/reason",
    deleteUrl: "/api/util/update/write-off/status",
    nameField: "name",
    statusChange: true,
    section: "masters",
  },
  {
    key: "business-group",
    title: "Business Group",
    description: "Business Group",
    getUrl: "/api/util/list/business/group",
    addUrl: "/api/util/add/business/group",
    deleteUrl: "/api/util/business/group/change/status",
    nameField: "name",
    statusChange: true,
    section: "masters",
  },
]

/** Settings-section tiles (mix of lookup + dedicated routes) */
export const SETTINGS_TILES: MasterConfig[] = [
  {
    key: "appearance",
    title: "Appearance",
    description: "Theme and language preferences",
    href: "/admin/settings/appearance",
    getUrl: "", addUrl: "", deleteUrl: "", nameField: "",
    section: "settings",
  },
  {
    key: "company-info",
    title: "Company Info",
    description: "Company details, currency, tax, and billing defaults",
    href: "/admin/settings/company",
    getUrl: "", addUrl: "", deleteUrl: "", nameField: "",
    section: "settings",
  },
  {
    key: "invoice-sequence",
    title: "Invoice Sequence",
    description: "Configure invoice sequences",
    href: "/admin/settings/invoice-sequence",
    getUrl: "", addUrl: "", deleteUrl: "", nameField: "",
    section: "settings",
  },
  {
    key: "onedrive-folder",
    title: "OneDrive Folder",
    description: "Setting up your OneDrive folders",
    href: "/admin/settings/masters/docs-type",
    getUrl: "", addUrl: "", deleteUrl: "", nameField: "",
    section: "settings",
  },
  {
    key: "my-dashboard",
    title: "My Dashboard",
    description: "Customize My dashboard",
    href: "/admin/settings/my-dashboard",
    getUrl: "", addUrl: "", deleteUrl: "", nameField: "",
    section: "settings",
  },
  {
    key: "groups",
    title: "Groups",
    description: "Configure Groups for users",
    href: "/admin/groups",
    getUrl: "", addUrl: "", deleteUrl: "", nameField: "",
    section: "settings",
  },
  {
    key: "custom-fields",
    title: "Custom Field",
    description: "Custom Field Master",
    href: "/admin/settings/custom-fields",
    getUrl: "", addUrl: "", deleteUrl: "", nameField: "",
    section: "settings",
  },
  {
    key: "working-days",
    title: "Working Days",
    description: "Setting up working days master",
    href: "/admin/settings/working-days",
    getUrl: "", addUrl: "", deleteUrl: "", nameField: "",
    section: "masters",
  },
  {
    key: "meeting-time",
    title: "Meeting Time",
    description: "Configure default meeting hours and slots",
    href: "/admin/settings/meeting-time",
    getUrl: "", addUrl: "", deleteUrl: "", nameField: "",
    section: "settings",
    keywords: "meeting calendar slot",
  },
  {
    key: "zoho-id",
    title: "Zoho Id Configuration",
    description: "Configure Zoho config id to clients",
    href: "/admin/settings/zoho/id",
    getUrl: "", addUrl: "", deleteUrl: "", nameField: "",
    section: "settings",
    keywords: "zoho",
  },
  {
    key: "zoho-integration",
    title: "Zoho Integration Options",
    description: "Configure Zoho integration options",
    href: "/admin/settings/zoho/integration",
    getUrl: "", addUrl: "", deleteUrl: "", nameField: "",
    section: "settings",
    keywords: "zoho",
  },
  {
    key: "zoho-ledgers",
    title: "Zoho Ledgers",
    description: "Manage Zoho Ledgers",
    href: "/admin/settings/zoho/ledgers",
    getUrl: "", addUrl: "", deleteUrl: "", nameField: "",
    section: "settings",
    keywords: "zoho",
  },
  {
    key: "analytics-permissions",
    title: "Analytics Permissions",
    description: "Configure Permissions for Analytics",
    href: "/admin/settings/analytics-permissions",
    getUrl: "", addUrl: "", deleteUrl: "", nameField: "",
    section: "settings",
  },
  {
    key: "user-notifications",
    title: "Manage Users Notifications",
    description: "Manage notification exclusions for users without timelog entry",
    href: "/admin/settings/user-notifications",
    getUrl: "", addUrl: "", deleteUrl: "", nameField: "",
    section: "settings",
  },
  {
    key: "credit-categories",
    title: "Manage Credit Categories",
    description: "Credit Categories for users",
    getUrl: "/api/util/list/credit/category",
    addUrl: "/api/util/add/credit/category",
    deleteUrl: "/api/util/credit/category/change/status",
    nameField: "name",
    statusChange: true,
    section: "settings",
  },
  {
    key: "matter-stop-working-reasons",
    title: "Matter stop working reasons",
    description: "Matter stop working reasons for users",
    getUrl: "/api/util/list/matter/stop/working/reason",
    addUrl: "/api/util/add/matter/stop/working/reason",
    deleteUrl: "/api/util/matter/stop/working/reason/change/status",
    nameField: "name",
    statusChange: true,
    section: "settings",
  },
  {
    key: "estimated-hours",
    title: "Estimated hours templates",
    description: "Manage estimated hours by designation",
    href: "/admin/settings/estimated-hours",
    getUrl: "", addUrl: "", deleteUrl: "", nameField: "",
    section: "settings",
  },
  {
    key: "team-roles",
    title: "Manage Team Roles",
    description: "Configure team roles by category for matter assignments",
    href: "/admin/settings/team-roles",
    getUrl: "", addUrl: "", deleteUrl: "", nameField: "",
    section: "settings",
  },
  {
    key: "conflict-check",
    title: "Conflict Check Excluded Terms",
    description: "Manage globally excluded terms used by Conflict Check matching",
    href: "/admin/settings/conflict-check",
    getUrl: "", addUrl: "", deleteUrl: "", nameField: "",
    section: "settings",
  },
  {
    key: "hr-income",
    title: "HR Income Types",
    description: "Payroll income components",
    getUrl: "/api/hr/master/list/income",
    addUrl: "/api/hr/master/income/add",
    deleteUrl: "/api/hr/master/income/change/status",
    nameField: "name",
    statusChange: true,
    section: "masters",
    keywords: "hr income payroll",
  },
  {
    key: "hr-deduction",
    title: "HR Deduction Types",
    description: "Payroll deduction components",
    getUrl: "/api/hr/master/list/deduction",
    addUrl: "/api/hr/master/deduction/add",
    deleteUrl: "/api/hr/master/deduction/change/status",
    nameField: "name",
    statusChange: true,
    section: "masters",
    keywords: "hr deduction payroll",
  },
  {
    key: "hr-grade",
    title: "HR Grades",
    description: "Salary grades with basic amount",
    getUrl: "/api/hr/master/grade/list",
    addUrl: "/api/hr/master/grade/add",
    deleteUrl: "/api/hr/master/grade/change/status",
    nameField: "name",
    extraFields: [{ key: "basicSalary", label: "Basic Salary", type: "number" }],
    statusChange: true,
    section: "masters",
    keywords: "hr grade payroll",
  },
  {
    key: "hr-leaves",
    title: "Leave Types",
    description: "Master leave types for applications",
    getUrl: "/api/leave/list/type",
    addUrl: "/api/leave/master/add",
    deleteUrl: "/api/leave/type/change/status",
    nameField: "type",
    statusChange: true,
    section: "masters",
    keywords: "hr leave types",
  },
]

export function getMasterByKey(key: string): MasterConfig | undefined {
  return [...LOOKUP_MASTERS, ...SETTINGS_TILES].find(m => m.key === key)
}

export function masterHref(m: MasterConfig): string {
  if (m.href) return m.href
  return `/admin/settings/masters/${m.key}`
}
