import { lazy, Suspense } from 'react'
import { createBrowserRouter, RouterProvider, Navigate } from 'react-router-dom'
import { CircularProgress, Box } from '@mui/material'
import { protectedLoader } from '@/middleware'
import { PERMISSIONS } from '@config/permissions'

const Spin = () => <Box sx={{ display: "flex", justifyContent: "center", alignItems: "center", minHeight: "60vh" }}><CircularProgress /></Box>
const L = (fn: () => Promise<{ default: React.ComponentType }>) => { const C = lazy(fn); return <Suspense fallback={<Spin />}><C /></Suspense> }

const AuthLayout = lazy(() => import('./app/(auth)/layout').then(m => ({ default: m.default })))
const MainLayout = lazy(() => import('./app/(dashboard)/layout').then(m => ({ default: m.default })))

const router = createBrowserRouter([
  { path: '/', element: <Navigate to="/dashboard" replace /> },
  {
    element: <Suspense fallback={<Spin />}><AuthLayout /></Suspense>,
    children: [
      { path: '/login',           element: L(() => import('./app/(auth)/login/page')) },
      { path: '/register',        element: L(() => import('./app/(auth)/register/page')) },
      { path: '/forgot-password', element: L(() => import('./app/(auth)/forgot-password/page')) },
      { path: '/lead/upload',     element: L(() => import('./app/(public)/lead-upload/page')) },
    ],
  },
  {
    element: <Suspense fallback={<Spin />}><MainLayout /></Suspense>,
    loader: protectedLoader(),
    children: [
      { path: '/dashboard',         loader: protectedLoader('/dashboard'),  element: L(() => import('./app/(dashboard)/dashboard/page')) },
      { path: '/department/analytics', loader: protectedLoader('/dashboard'), element: L(() => import('./app/(dashboard)/department/analytics/page')) },
      { path: '/leads',             loader: protectedLoader('/leads'),       element: L(() => import('./app/(dashboard)/leads/page')) },
      { path: '/leads/:leadId',     loader: protectedLoader('/leads'),       element: L(() => import('./app/(dashboard)/leads/[leadId]/page')) },
      { path: '/my-leads/:leadId',  loader: protectedLoader('/my-leads'),    element: L(() => import('./app/(dashboard)/leads/[leadId]/page')) },
      { path: '/my-leads',          loader: protectedLoader('/my-leads'),    element: L(() => import('./app/(dashboard)/my-leads/page')) },
      { path: '/clients',           loader: protectedLoader('/clients'),     element: L(() => import('./app/(dashboard)/clients/page')) },
      { path: '/clients/:clientId', loader: protectedLoader('/clients'),     element: L(() => import('./app/(dashboard)/clients/[clientId]/page')) },
      { path: '/matters/check-conflict', loader: protectedLoader('/matters'), element: L(() => import('./app/(dashboard)/matters/check-conflict/page')) },
      { path: '/matters/requests',  loader: protectedLoader('/matters'),     element: L(() => import('./app/(dashboard)/matters/requests/page')) },
      { path: '/matters/short',     loader: protectedLoader(PERMISSIONS.MATTERS_VIEW), element: L(() => import('./app/(dashboard)/matters/short/page')) },
      { path: '/matters/short/:shortMatterId', loader: protectedLoader(PERMISSIONS.MATTERS_VIEW), element: L(() => import('./app/(dashboard)/matters/short/[shortMatterId]/page')) },
      { path: '/matters/pending',   loader: protectedLoader(PERMISSIONS.MATTERS_VIEW), element: L(() => import('./app/(dashboard)/matters/pending/page')) },
      { path: '/matters',           loader: protectedLoader('/matters'),     element: L(() => import('./app/(dashboard)/matters/page')) },
      { path: '/matters/:matterId', loader: protectedLoader('/matters'),     element: L(() => import('./app/(dashboard)/matters/[matterId]/page')) },
      { path: '/hearings',          loader: protectedLoader(PERMISSIONS.MATTERS_VIEW), element: L(() => import('./app/(dashboard)/hearings/page')) },
      { path: '/hearings/history',  loader: protectedLoader(PERMISSIONS.MATTERS_VIEW), element: L(() => import('./app/(dashboard)/hearings/history/page')) },
      { path: '/hearings/:hearingId', loader: protectedLoader(PERMISSIONS.MATTERS_VIEW), element: L(() => import('./app/(dashboard)/hearings/[hearingId]/page')) },
      { path: '/hearing',           loader: protectedLoader(PERMISSIONS.MATTERS_VIEW), element: L(() => import('./app/(dashboard)/hearings/_components/LegacyHearingRedirect')) },
      { path: '/payment',           loader: protectedLoader('/billings'),    element: L(() => import('./app/(dashboard)/payment/page')) },
      { path: '/billing',            loader: protectedLoader('/billings'),    element: L(() => import('./app/(dashboard)/billing/page')) },
      { path: '/reports',           loader: protectedLoader('/reports/wip'), element: L(() => import('./app/(dashboard)/reports/page')) },
      { path: '/internal-leads',    loader: protectedLoader('/leads'),       element: L(() => import('./app/(dashboard)/internal-leads/page')) },
      { path: '/payrolls',          loader: protectedLoader('/payrolls'),    element: L(() => import('./app/(dashboard)/payrolls/page')) },
      { path: '/time-log-entries',  loader: protectedLoader('/time-log-entries'),    element: L(() => import('./app/(dashboard)/time-log-entries/page')) },
          { path: '/time-log-entries/:entryId', loader: protectedLoader(), element: L(() => import('./app/(dashboard)/time-log-entries/[entryId]/page')) },
      { path: '/calendar',          loader: protectedLoader('/calendar'),    element: L(() => import('./app/(dashboard)/calendar/page')) },
      { path: '/tasks',             loader: protectedLoader('/tasks'),       element: L(() => import('./app/(dashboard)/tasks/page')) },
      { path: '/tasks/templates',    loader: protectedLoader('/tasks'),       element: L(() => import('./app/(dashboard)/tasks/templates/page')) },
      { path: '/tasks/templates/:templateId', loader: protectedLoader('/tasks'), element: L(() => import('./app/(dashboard)/task-templates/[templateId]/page')) },
      { path: '/task-templates',     loader: protectedLoader('/tasks'),       element: L(() => import('./app/(dashboard)/tasks/templates/page')) },
      { path: '/task-templates/:templateId', loader: protectedLoader('/tasks'), element: L(() => import('./app/(dashboard)/task-templates/[templateId]/page')) },
      { path: '/tasks/:taskId',     loader: protectedLoader('/tasks'),       element: L(() => import('./app/(dashboard)/tasks/[taskId]/page')) },
      { path: '/billings',              loader: protectedLoader('/billings'), element: L(() => import('./app/(dashboard)/billings/page')) },
      { path: '/billings/invoices',      loader: protectedLoader('/billings'), element: L(() => import('./app/(dashboard)/billings/page')) },
      { path: '/billings/expense',       loader: protectedLoader('/billings'), element: L(() => import('./app/(dashboard)/billings/expense/page')) },
      { path: '/billings/contingent',    loader: protectedLoader('/billings'), element: L(() => import('./app/(dashboard)/billings/contingent/page')) },
      { path: '/billings/non-contingent',loader: protectedLoader('/billings'), element: L(() => import('./app/(dashboard)/billings/non-contingent/page')) },
      { path: '/billings/success-rate',  loader: protectedLoader('/billings'), element: L(() => import('./app/(dashboard)/billings/success-rate/page')) },
      { path: '/billings/enforcement',   loader: protectedLoader('/billings'), element: L(() => import('./app/(dashboard)/billings/enforcement/page')) },
      { path: '/billings/receipts',      loader: protectedLoader('/billings'), element: L(() => import('./app/(dashboard)/billings/receipts/page')) },
      { path: '/billings/credit-notes',  loader: protectedLoader('/billings'), element: L(() => import('./app/(dashboard)/billings/credit-notes/page')) },
      { path: '/billings/retainer',      loader: protectedLoader('/billings'), element: L(() => import('./app/(dashboard)/billings/retainer/page')) },
      { path: '/billings/retainer-statements', loader: protectedLoader('/billings'), element: L(() => import('./app/(dashboard)/billings/retainer-statements/page')) },
      { path: '/billings/retainer-history', loader: protectedLoader('/billings'), element: L(() => import('./app/(dashboard)/billings/retainer-history/page')) },
      { path: '/billings/write-off',     loader: protectedLoader('/billings'), element: L(() => import('./app/(dashboard)/billings/write-off/page')) },
      { path: '/billings/write-off/:invoiceId', loader: protectedLoader('/billings'), element: L(() => import('./app/(dashboard)/billings/write-off/page')) },
      { path: '/billings/:invoiceId',    loader: protectedLoader('/billings'), element: L(() => import('./app/(dashboard)/billings/[invoiceId]/page')) },
      { path: '/vendors',               loader: protectedLoader('/vendors'),  element: L(() => import('./app/(dashboard)/vendors/page')) },
      { path: '/vendors/:vendorId',     loader: protectedLoader('/vendors'),  element: L(() => import('./app/(dashboard)/vendors/[vendorId]/page')) },
      { path: '/leaves',                loader: protectedLoader('/leaves'),   element: L(() => import('./app/(dashboard)/leaves/page')) },
      { path: '/leave-applications',    loader: protectedLoader('/leave-applications'), element: L(() => import('./app/(dashboard)/leaves/applications/page')) },
      { path: '/admin/bank-accounts',   loader: protectedLoader('/accounts'), element: L(() => import('./app/(dashboard)/admin/bank-accounts/page')) },
      { path: '/approvals/invoice', loader: protectedLoader('/approvals/invoice'),  element: L(() => import('./app/(dashboard)/approvals/invoice/page')) },
      { path: '/approvals/lfa',     loader: protectedLoader(PERMISSIONS.LFA_APPROVE),      element: L(() => import('./app/(dashboard)/approvals/lfa/page')) },
      { path: '/approvals/task',    loader: protectedLoader('/tasks'),       element: L(() => import('./app/(dashboard)/approvals/task/page')) },
      // LMS email/notification parity — approve-invoice deep links
      { path: '/:attorneyId/:invoiceId/approve-invoice', loader: protectedLoader('/approvals/invoice'), element: L(() => import('./app/(dashboard)/approvals/invoice/_components/LegacyApproveInvoiceRedirect')) },
      { path: '/:attorneyId/:invoiceId/approve-invoice/:invoiceNumber/:invoicePrefix/:approveId/:matterId', loader: protectedLoader('/approvals/invoice'), element: L(() => import('./app/(dashboard)/approvals/invoice/_components/LegacyApproveInvoiceRedirect')) },
      { path: '/:attorneyId/:invoiceId/approve-department-invoice/:invoiceNumber/:invoicePrefix/:approveId/:matterId/:isDepartment', loader: protectedLoader(PERMISSIONS.BILLING_APPROVE), element: L(() => import('./app/(dashboard)/approvals/invoice/_components/LegacyApproveInvoiceRedirect')) },
      { path: '/lfa',               loader: protectedLoader('/lfa'),         element: L(() => import('./app/(dashboard)/lfa/page')) },
      { path: '/lfa/default',       loader: protectedLoader('/lfa'),         element: L(() => import('./app/(dashboard)/lfa/default/page')) },
      { path: '/lfa/reports',       loader: protectedLoader('/lfa'),         element: L(() => import('./app/(dashboard)/lfa/reports/page')) },
      { path: '/lfa/client',        loader: protectedLoader('/lfa'),         element: L(() => import('./app/(dashboard)/lfa/client/page')) },
      { path: '/lfa/:lfaId/amend',  loader: protectedLoader('/lfa'),         element: L(() => import('./app/(dashboard)/lfa/[lfaId]/amend/page')) },
      { path: '/lfa/:lfaId/partial-amend', loader: protectedLoader('/lfa'),  element: L(() => import('./app/(dashboard)/lfa/[lfaId]/partial-amend/page')) },
      { path: '/lfa/:lfaId',        loader: protectedLoader('/lfa'),         element: L(() => import('./app/(dashboard)/lfa/[lfaId]/page')) },
      { path: '/reports/wip',           loader: protectedLoader('/reports/wip'), element: L(() => import('./app/(dashboard)/reports/wip/page')) },
      { path: '/reports/billed-amount', loader: protectedLoader('/reports/wip'), element: L(() => import('./app/(dashboard)/reports/billed-amount/page')) },
      { path: '/reports/matter-billing',loader: protectedLoader('/reports/wip'), element: L(() => import('./app/(dashboard)/reports/matter-billing/page')) },
      { path: '/reports/utilization',   loader: protectedLoader('/reports/wip'), element: L(() => import('./app/(dashboard)/reports/utilization/page')) },
      { path: '/reports/activity-history', loader: protectedLoader('/reports/wip'), element: L(() => import('./app/(dashboard)/reports/activity-history/page')) },
      { path: '/reports/margin-erosion',   loader: protectedLoader('/reports/wip'), element: L(() => import('./app/(dashboard)/reports/margin-erosion/page')) },
      { path: '/reports/collections',      loader: protectedLoader('/reports/wip'), element: L(() => import('./app/(dashboard)/reports/collections/page')) },
      { path: '/reports/aging',            loader: protectedLoader('/reports/wip'), element: L(() => import('./app/(dashboard)/reports/aging/page')) },
      { path: '/reports/dues',             loader: protectedLoader('/reports/wip'), element: L(() => import('./app/(dashboard)/reports/dues/page')) },
      { path: '/reports/matters',          loader: protectedLoader('/reports/wip'), element: L(() => import('./app/(dashboard)/reports/matters/page')) },
      { path: '/reports/tasks',            loader: protectedLoader('/reports/wip'), element: L(() => import('./app/(dashboard)/reports/tasks/page')) },
      { path: '/reports/hearings',         loader: protectedLoader('/reports/wip'), element: L(() => import('./app/(dashboard)/reports/hearings/page')) },
      { path: '/reports/profit-loss',      loader: protectedLoader('/reports/wip'), element: L(() => import('./app/(dashboard)/reports/profit-loss/page')) },
      { path: '/reports/attorney-revenue', loader: protectedLoader('/reports/wip'), element: L(() => import('./app/(dashboard)/reports/attorney-revenue/page')) },
      { path: '/reports/referral',         loader: protectedLoader('/reports/wip'), element: L(() => import('./app/(dashboard)/reports/referral/page')) },
      { path: '/reports/non-converted-leads', loader: protectedLoader('/reports/wip'), element: L(() => import('./app/(dashboard)/reports/non-converted-leads/page')) },
      { path: '/reports/purged-discounted', loader: protectedLoader('/reports/wip'), element: L(() => import('./app/(dashboard)/reports/purged-discounted/page')) },
      { path: '/reports/cost-analysis',    loader: protectedLoader('/reports/wip'), element: L(() => import('./app/(dashboard)/reports/cost-analysis/page')) },
      { path: '/reports/zoho-outstanding', loader: protectedLoader('/reports/wip'), element: L(() => import('./app/(dashboard)/reports/zoho-outstanding/page')) },
      { path: '/reports/invoices',         loader: protectedLoader('/reports/wip'), element: L(() => import('./app/(dashboard)/reports/invoices/page')) },
      { path: '/reports/leads',            loader: protectedLoader('/reports/wip'), element: L(() => import('./app/(dashboard)/reports/leads/page')) },
      { path: '/reports/activities',       loader: protectedLoader('/reports/wip'), element: L(() => import('./app/(dashboard)/reports/activities/page')) },
      { path: '/reports/deposit-balance',  loader: protectedLoader('/reports/wip'), element: L(() => import('./app/(dashboard)/reports/deposit-balance/page')) },
      { path: '/reports/user-timelog-entries', loader: protectedLoader('/reports/wip'), element: L(() => import('./app/(dashboard)/reports/user-timelog-entries/page')) },
      { path: '/reports/rating', loader: protectedLoader('/reports/wip'), element: L(() => import('./app/(dashboard)/reports/rating/page')) },
      { path: '/reports/posts', loader: protectedLoader('/reports/wip'), element: L(() => import('./app/(dashboard)/reports/posts/page')) },
      { path: '/reports/wip-department', loader: protectedLoader('/reports/wip'), element: L(() => import('./app/(dashboard)/reports/wip-department/page')) },
      { path: '/reports/wip-attorney', loader: protectedLoader('/reports/wip'), element: L(() => import('./app/(dashboard)/reports/wip-attorney/page')) },
      { path: '/reports/wip-matter', loader: protectedLoader('/reports/wip'), element: L(() => import('./app/(dashboard)/reports/wip-matter/page')) },
      { path: '/reports/retainer-statement', loader: protectedLoader('/reports/wip'), element: L(() => import('./app/(dashboard)/reports/retainer-statement/page')) },
      { path: '/reports/matter-summary', loader: protectedLoader('/reports/wip'), element: L(() => import('./app/(dashboard)/reports/matter-summary/page')) },
      { path: '/reports/closed-matters', loader: protectedLoader('/reports/wip'), element: L(() => import('./app/(dashboard)/reports/closed-matters/page')) },
      { path: '/reports/fee-earner-billed', loader: protectedLoader('/reports/wip'), element: L(() => import('./app/(dashboard)/reports/fee-earner-billed/page')) },
      { path: '/reports/task-average', loader: protectedLoader('/reports/wip'), element: L(() => import('./app/(dashboard)/reports/task-average/page')) },
      { path: '/reports/fixed-balance', loader: protectedLoader('/reports/wip'), element: L(() => import('./app/(dashboard)/reports/fixed-balance/page')) },
      { path: '/reports/billing-by-lfa', loader: protectedLoader('/reports/wip'), element: L(() => import('./app/(dashboard)/reports/billing-by-lfa/page')) },
      { path: '/reports/billable-by-department', loader: protectedLoader('/reports/wip'), element: L(() => import('./app/(dashboard)/reports/billable-by-department/page')) },
      { path: '/reports/audit', loader: protectedLoader('/reports/wip'), element: L(() => import('./app/(dashboard)/reports/audit/page')) },
      { path: '/reports/onedrive', loader: protectedLoader('/reports/wip'), element: L(() => import('./app/(dashboard)/reports/onedrive/page')) },
      { path: '/reports/favourite-clients', loader: protectedLoader('/reports/wip'), element: L(() => import('./app/(dashboard)/reports/favourite-clients/page')) },
      { path: '/reports/favourite-clients/:clientId', loader: protectedLoader('/reports/wip'), element: L(() => import('./app/(dashboard)/reports/favourite-clients/[clientId]/page')) },
      { path: '/reports/fixedfee-revenue-allocation', loader: protectedLoader('/reports/wip'), element: L(() => import('./app/(dashboard)/reports/fixedfee-revenue-allocation/page')) },
      { path: '/reports/procured-by', loader: protectedLoader('/reports/wip'), element: L(() => import('./app/(dashboard)/reports/procured-by/page')) },
      { path: '/reports/lead-value', loader: protectedLoader('/reports/wip'), element: L(() => import('./app/(dashboard)/reports/lead-value/page')) },
      { path: '/reports/leads-reduction', loader: protectedLoader('/reports/wip'), element: L(() => import('./app/(dashboard)/reports/leads-reduction/page')) },
      { path: '/reports/matter-revenue-summary', loader: protectedLoader('/reports/wip'), element: L(() => import('./app/(dashboard)/reports/matter-revenue-summary/page')) },
      { path: '/reports/estimate-hours-by-designation', loader: protectedLoader('/reports/wip'), element: L(() => import('./app/(dashboard)/reports/estimate-hours-by-designation/page')) },
      { path: '/reports/revenue-budget', loader: protectedLoader('/reports/wip'), element: L(() => import('./app/(dashboard)/reports/revenue-budget/page')) },
      { path: '/reports/billing-rate-analysis', loader: protectedLoader('/reports/wip'), element: L(() => import('./app/(dashboard)/reports/billing-rate-analysis/page')) },
      { path: '/reports/matter-billing-snapshot', loader: protectedLoader('/reports/wip'), element: L(() => import('./app/(dashboard)/reports/matter-billing-snapshot/page')) },
      { path: '/reports/margin-erosion-cache', loader: protectedLoader('/reports/wip'), element: L(() => import('./app/(dashboard)/reports/margin-erosion-cache/page')) },

      { path: '/clients/transfer', loader: protectedLoader(PERMISSIONS.CLIENTS_VIEW), element: L(() => import('./app/(dashboard)/clients/transfer/page')) },
      { path: '/clients/referral-partners', loader: protectedLoader(PERMISSIONS.CLIENTS_VIEW), element: L(() => import('./app/(dashboard)/clients/referral-partners/page')) },
      { path: '/tasks/multi-step', loader: protectedLoader(PERMISSIONS.TASKS_VIEW), element: L(() => import('./app/(dashboard)/tasks/multi-step/page')) },
      { path: '/document-reminders', loader: protectedLoader(PERMISSIONS.MATTERS_VIEW), element: L(() => import('./app/(dashboard)/document-reminders/page')) },
      { path: '/editor', loader: protectedLoader(PERMISSIONS.MATTERS_VIEW), element: L(() => import('./app/(dashboard)/editor/page')) },
      { path: '/documents/editor', loader: protectedLoader(PERMISSIONS.MATTERS_VIEW), element: L(() => import('./app/(dashboard)/editor/page')) },
      { path: '/billings/translation-courier', loader: protectedLoader(PERMISSIONS.BILLING_VIEW), element: L(() => import('./app/(dashboard)/billings/translation-courier/page')) },
      { path: '/billings/invoice-snaps', loader: protectedLoader(PERMISSIONS.BILLING_VIEW), element: L(() => import('./app/(dashboard)/billings/invoice-snaps/page')) },
      { path: '/approvals/department-invoice', loader: protectedLoader(PERMISSIONS.BILLING_APPROVE), element: L(() => import('./app/(dashboard)/approvals/department-invoice/page')) },
      { path: '/approvals/department-activity', loader: protectedLoader(PERMISSIONS.TIMELOGS_APPROVE), element: L(() => import('./app/(dashboard)/approvals/department-activity/page')) },
      { path: '/admin/settings/meeting-time', loader: protectedLoader(PERMISSIONS.SETTINGS_VIEW), element: L(() => import('./app/(dashboard)/admin/settings/meeting-time/page')) },
      { path: '/team',                  loader: protectedLoader(PERMISSIONS.TEAM_VIEW),    element: L(() => import('./app/(dashboard)/team/page')) },
      { path: '/team/templates',        loader: protectedLoader(PERMISSIONS.TEAM_VIEW),    element: L(() => import('./app/(dashboard)/team/templates/page')) },
      { path: '/team/templates/:templateId', loader: protectedLoader(PERMISSIONS.TEAM_VIEW), element: L(() => import('./app/(dashboard)/team/templates/[templateId]/page')) },
      { path: '/team/hearing-calendar', loader: protectedLoader(PERMISSIONS.TEAM_VIEW),    element: L(() => import('./app/(dashboard)/team/hearing-calendar/page')) },
      { path: '/team/upcoming-hearings', loader: protectedLoader(PERMISSIONS.TEAM_VIEW),   element: L(() => import('./app/(dashboard)/team/upcoming-hearings/page')) },
      { path: '/team/member/:memberId', loader: protectedLoader(PERMISSIONS.TEAM_VIEW),   element: L(() => import('./app/(dashboard)/team/member/[memberId]/page')) },
      { path: '/team/:teamId',          loader: protectedLoader(PERMISSIONS.TEAM_VIEW),    element: L(() => import('./app/(dashboard)/team/[teamId]/page')) },
      { path: '/timelogs/review',       loader: protectedLoader(PERMISSIONS.TIMELOGS_APPROVE), element: L(() => import('./app/(dashboard)/timelogs/review/page')) },
      { path: '/timelogs/pre-approval', loader: protectedLoader(PERMISSIONS.TIMELOGS_APPROVE), element: L(() => import('./app/(dashboard)/timelogs/pre-approval/page')) },
      { path: '/timelogs/approval',     loader: protectedLoader(PERMISSIONS.TIMELOGS_APPROVE), element: L(() => import('./app/(dashboard)/timelogs/approval/page')) },
      { path: '/timelogs/pending',      loader: protectedLoader(PERMISSIONS.TIMELOGS_APPROVE), element: L(() => import('./app/(dashboard)/timelogs/pending/page')) },
      { path: '/timelogs/approved',     loader: protectedLoader(PERMISSIONS.TIMELOGS_VIEW), element: L(() => import('./app/(dashboard)/timelogs/approved/page')) },
      { path: '/billings/history',      loader: protectedLoader('/billings'), element: L(() => import('./app/(dashboard)/billings/history/page')) },
      { path: '/matter-selection',      loader: protectedLoader(PERMISSIONS.TIMELOGS_CREATE), element: L(() => import('./app/(dashboard)/matter-selection/page')) },
      { path: '/integrations/onedrive', loader: protectedLoader(PERMISSIONS.ONEDRIVE_VIEW),element: L(() => import('./app/(dashboard)/integrations/onedrive/page')) },
      { path: '/budgeting/cost-cards',  loader: protectedLoader(PERMISSIONS.BUDGETING_VIEW), element: L(() => import('./app/(dashboard)/budgeting/cost-cards/page')) },
      { path: '/budgeting/budget-cards',loader: protectedLoader(PERMISSIONS.BUDGETING_VIEW), element: L(() => import('./app/(dashboard)/budgeting/budget-cards/page')) },
      { path: '/budgeting/rate-cards',  loader: protectedLoader(PERMISSIONS.BUDGETING_VIEW), element: L(() => import('./app/(dashboard)/budgeting/rate-cards/page')) },
      { path: '/rate-cards',            loader: protectedLoader(PERMISSIONS.BUDGETING_VIEW), element: L(() => import('./app/(dashboard)/rate-cards/page')) },
      { path: '/admin/users',       loader: protectedLoader(PERMISSIONS.USERS_VIEW),       element: L(() => import('./app/(dashboard)/admin/users/page')) },
      { path: '/admin/teams',       loader: protectedLoader(PERMISSIONS.TEAM_MANAGE),      element: L(() => import('./app/(dashboard)/admin/teams/page')) },
      { path: '/admin/teams/:teamId', loader: protectedLoader(PERMISSIONS.TEAM_MANAGE),    element: L(() => import('./app/(dashboard)/admin/teams/[teamId]/page')) },
      { path: '/admin/groups',      loader: protectedLoader(PERMISSIONS.GROUPS_VIEW),      element: L(() => import('./app/(dashboard)/admin/groups/page')) },
      { path: '/admin/permissions', loader: protectedLoader(PERMISSIONS.GROUPS_MANAGE),    element: L(() => import('./app/(dashboard)/admin/permissions/page')) },
      { path: '/admin/individual-permissions', loader: protectedLoader(PERMISSIONS.GROUPS_MANAGE), element: L(() => import('./app/(dashboard)/admin/individual-permissions/page')) },
      { path: '/admin/activity-access', loader: protectedLoader(PERMISSIONS.GROUPS_MANAGE), element: L(() => import('./app/(dashboard)/admin/activity-access/page')) },
      { path: '/admin/extra-permissions', loader: protectedLoader(PERMISSIONS.GROUPS_MANAGE), element: L(() => import('./app/(dashboard)/admin/extra-permissions/page')) },
      { path: '/admin/locations',   loader: protectedLoader(PERMISSIONS.LOCATIONS_VIEW),   element: L(() => import('./app/(dashboard)/admin/locations/page')) },
      { path: '/matters/:matterId/mail/:emailId', loader: protectedLoader(PERMISSIONS.MATTERS_VIEW), element: L(() => import('./app/(dashboard)/matters/mail/[emailId]/page')) },
      { path: '/matter-mail/:emailId', loader: protectedLoader(PERMISSIONS.MATTERS_VIEW), element: L(() => import('./app/(dashboard)/matters/mail/[emailId]/page')) },
      { path: '/admin/audit-log',   loader: protectedLoader(PERMISSIONS.SETTINGS_VIEW),   element: L(() => import('./app/(dashboard)/admin/audit-log/page')) },
      { path: '/admin/settings',    loader: protectedLoader(PERMISSIONS.SETTINGS_VIEW),    element: L(() => import('./app/(dashboard)/admin/settings/page')) },
      { path: '/admin/settings/company', loader: protectedLoader(PERMISSIONS.SETTINGS_VIEW), element: L(() => import('./app/(dashboard)/admin/settings/company/page')) },
      { path: '/admin/settings/appearance', loader: protectedLoader(PERMISSIONS.SETTINGS_VIEW), element: L(() => import('./app/(dashboard)/admin/settings/appearance/page')) },
      { path: '/admin/settings/masters/:key', loader: protectedLoader(PERMISSIONS.SETTINGS_VIEW), element: L(() => import('./app/(dashboard)/admin/settings/masters/[key]/page')) },
      { path: '/admin/settings/working-days', loader: protectedLoader(PERMISSIONS.SETTINGS_VIEW), element: L(() => import('./app/(dashboard)/admin/settings/working-days/page')) },
      { path: '/admin/settings/my-dashboard', loader: protectedLoader(PERMISSIONS.SETTINGS_VIEW), element: L(() => import('./app/(dashboard)/admin/settings/my-dashboard/page')) },
      { path: '/admin/settings/invoice-sequence', loader: protectedLoader(PERMISSIONS.SETTINGS_VIEW), element: L(() => import('./app/(dashboard)/admin/settings/invoice-sequence/page')) },
      { path: '/admin/settings/custom-fields', loader: protectedLoader(PERMISSIONS.SETTINGS_VIEW), element: L(() => import('./app/(dashboard)/admin/settings/custom-fields/page')) },
      { path: '/admin/settings/conflict-check', loader: protectedLoader(PERMISSIONS.SETTINGS_VIEW), element: L(() => import('./app/(dashboard)/admin/settings/conflict-check/page')) },
      { path: '/admin/settings/user-notifications', loader: protectedLoader(PERMISSIONS.SETTINGS_VIEW), element: L(() => import('./app/(dashboard)/admin/settings/user-notifications/page')) },
      { path: '/admin/settings/team-roles', loader: protectedLoader(PERMISSIONS.SETTINGS_VIEW), element: L(() => import('./app/(dashboard)/admin/settings/team-roles/page')) },
      { path: '/admin/settings/estimated-hours', loader: protectedLoader(PERMISSIONS.SETTINGS_VIEW), element: L(() => import('./app/(dashboard)/admin/settings/estimated-hours/page')) },
      { path: '/admin/settings/designations', loader: protectedLoader(PERMISSIONS.SETTINGS_VIEW), element: L(() => import('./app/(dashboard)/admin/settings/designations/page')) },
      { path: '/admin/settings/departments', loader: protectedLoader(PERMISSIONS.SETTINGS_VIEW), element: L(() => import('./app/(dashboard)/admin/settings/departments/page')) },
      { path: '/admin/settings/lead-sources', loader: protectedLoader(PERMISSIONS.SETTINGS_VIEW), element: L(() => import('./app/(dashboard)/admin/settings/lead-sources/page')) },
      { path: '/admin/settings/practice-areas', loader: protectedLoader(PERMISSIONS.SETTINGS_VIEW), element: L(() => import('./app/(dashboard)/admin/settings/practice-areas/page')) },
      { path: '/admin/settings/refer-client', loader: protectedLoader(PERMISSIONS.SETTINGS_VIEW), element: L(() => import('./app/(dashboard)/admin/settings/refer-client/page')) },
      { path: '/admin/settings/analytics-permissions', loader: protectedLoader(PERMISSIONS.SETTINGS_VIEW), element: L(() => import('./app/(dashboard)/admin/settings/analytics-permissions/page')) },
      { path: '/admin/settings/zoho/id', loader: protectedLoader(PERMISSIONS.SETTINGS_VIEW), element: L(() => import('./app/(dashboard)/admin/settings/zoho/id/page')) },
      { path: '/admin/settings/zoho/integration', loader: protectedLoader(PERMISSIONS.SETTINGS_VIEW), element: L(() => import('./app/(dashboard)/admin/settings/zoho/integration/page')) },
      { path: '/admin/settings/zoho/ledgers', loader: protectedLoader(PERMISSIONS.SETTINGS_VIEW), element: L(() => import('./app/(dashboard)/admin/settings/zoho/ledgers/page')) },
      { path: '/profile',           loader: protectedLoader(),                             element: L(() => import('./app/(dashboard)/profile/page')) },
      { path: '/activities',        loader: protectedLoader('/time-log-entries'),          element: L(() => import('./app/(dashboard)/activities/page')) },
      { path: '/matters/print',     loader: protectedLoader('/matters'),                   element: L(() => import('./app/(dashboard)/matters/print/page')) },
      { path: '/tickets',           loader: protectedLoader('/tickets'),                   element: L(() => import('./app/(dashboard)/tickets/page')) },
      { path: '/tickets/:ticketId', loader: protectedLoader('/tickets'),                   element: L(() => import('./app/(dashboard)/tickets/[ticketId]/page')) },
      { path: '/edit/tickets/:ticketId', loader: protectedLoader('/tickets'),              element: L(() => import('./app/(dashboard)/tickets/[ticketId]/page')) },
      { path: '/email',             loader: protectedLoader('/email'),                     element: L(() => import('./app/(dashboard)/email/page')) },
    ],
  },
  {
    path: '/billings/print',
    loader: protectedLoader('/billings'),
    element: L(() => import('./app/(dashboard)/billings/print/page')),
  },
  { path: '/403', element: <Box sx={{ p: 4 }}><h2>403 — Access Denied</h2></Box> },
  { path: 'forbidden', lazy: () => import('./app/forbidden/page').then(m => ({ Component: m.default })) },
  { path: '*', lazy: () => import('./app/not-found/page').then(m => ({ Component: m.default })) },
])

export function AppRouter() { return <RouterProvider router={router} /> }
